### ISSUE TITLE
Memory size ...

### ISSUE THREAD

**Issue by vsraptor** [huydhn/cuckoo-filter#3]
How do I get the size in bytes of the filter/s

**Comment by vsraptor** [comment]
is this OK

```
def nbytes(self):
	rv = 0
	for filt in self.filters : 
		rv += len(filt.buckets)/8
	return rv
	
ScalableCuckooFilter.nbytes = nbytes		

```

**Comment by huydhn** [comment]
Sorry, I haven't worked on this for such a long time, so I need to re-read my own code to answer this question. The ScalableCuckooFilter is basically a collection of multiple fixed-size filters. Each filter has a bit array keeping all the fingerprints. So the size in bytes could be calculated exactly as your solution suggests.
